apiVersion: v1
kind: Pod
metadata: 
  name: flask
  labels:
    app: flask-app
spec: 
  containers: 
  - name: flask
    image: mcmuds/task2-app # Dockerhub
    imagePullPolicy: Always
    # ports: 
    # - containerPort: 5000
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: Pa$$w0rd
---
apiVersion: v1
kind: Service
metadata: 
  name: flask-app
spec: 
  type: ClusterIP
  selector: 
    app: flask-app
  ports:
  - protocol: TCP
    port: 5000
    # targetPort: 5000
---
apiVersion: v1
kind: Pod
metadata: 
  name: mysql
  labels:
    app: task2-db
spec: 
  containers: 
  - name: flask
    image: mcmuds/task2-db:latest # Dockerhub
    imagePullPolicy: Always
    ports: 
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: Pa$$w0rd
---
apiVersion: v1
kind: Service
metadata: 
  name: mysql
spec: 
  type: ClusterIP
  selector: 
    app: task2-db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
